---
- name: Playbook to display info on a host
  hosts: localhost
  gather_facts: false
  become: true
  vars_files:
    - falcon_vars.yml

  tasks:

    - name: Lets do a one time Authentication to the Falcon server for the Play
      crowdstrike.falcon.auth:
        client_id: "{{ falcon_client_id }}"
        client_secret: "{{ falcon_client_secret }}"
        cloud: "{{ falcon_cloud }}"
        action: generate
      register: falcon_oauth

    - name: Look at a host status in Crowdstrike Falcon
      crowdstrike.falcon.host_info:
        auth: "{{ falcon_oauth.auth }}"
        hosts:
          - "91b3f1b26317403fa1f0ad37fd989bdf"
      register: host_info

    - name: Display host status
      ansible.builtin.debug:
        var: host_info