---
- name: A Playbook to install the Crowdstrike sensor
  hosts: caesar.thenorvilles.com
  gather_facts: true
  become: true
  vars_files: 
    - falcon_vars.yml    

  roles:

    - role: crowdstrike.falcon.falcon_install

