---
- name: Listen for CrowdStrike Falcon detection events - Smoke Test
  hosts: localhost
  sources:
    - crowdstrike.falcon.eventstream:
        falcon_client_id: "{{ client_id }}"
        falcon_client_secret: "{{ client_secret }}"
        falcon_cloud: "{{ cloud }}"
        stream_name: Crowdstrike
        latest: true
        include_event_types:
          - "DetectionSummaryEvent"
  
  rules:
    - name: EDA - Crowdstrike Events from the Falcon Console - Kickoff a playbook
      condition: event.falcon is defined
      action:
        run_job_template:
          name: 'EDA - Basic Test'
          organization: 'Default'