---
- name: Listen for CrowdStrike Falcon detection events - Smoke Test
  hosts: localhost
  sources:
    - crowdstrike.falcon.eventstream:
        falcon_client_id: "{{ client_id }}"
        falcon_client_secret: "{{ client_secret }}"
        falcon_cloud: "{{ cloud }}"
        stream_name: Crowdstrike
        latest: true
        include_event_types:
          - "DetectionSummaryEvent"
  
  rules:
    - name: EDA - Crowdstrike Events from the Falcon Console - Kickoff a playbook
      condition: event.falcon is defined
      action:
        run_job_template:
          name: 'Crowdstrike - Contain Host & Open SNOW Incident'
          organization: 'Default'
          job_args:
            extra_vars:
              cs_computer_name: "{{ event.falcon.event.ComputerName }}"
              cs_description: "{{ event.falcon.event.DetectDescription }}"
              cs_commandline: "{{ event.falcon.event.CommandLine }}"
              cs_classisfication: "{{ event.falcon.event.DetectName }}"
              cs_local_ip: "{{ event.falcon.event.LocalIP }}"
              cs_mac_addr: "{{ event.falcon.event.MACAddress }}"
              cs_severity: "{{ event.falcon.event.Severity }}"
              cs_severity_name: "{{ event.falcon.event.SeverityName }}"
              cs_tactic: "{{ event.falcon.event.Tactic }}"
              cs_technique: "{{ event.falcon.event.Technique }}"
              cs_username: "{{ event.falcon.event.UserName }}"
              cs_sensor_id: "{{ event.falcon.event.SensorId }}"
