---
- name: Listen for CrowdStrike Falcon detection events
  hosts: localhost
  sources:
    - crowdstrike.falcon.eventstream:
        falcon_client_id: "{{ CS_FALCON_CLIENT_ID }}"
        falcon_client_secret: "{{ CS_FALCON_CLIENT_SECRET }}"
        falcon_cloud: "{{ CS_FALCON_CLOUD }}"
        stream_name: Crowdstrike
        latest: true
        include_event_types:
          - "DetectionSummaryEvent"
  
  rules:
    - name: EDA - Crowdstrike Events from the Falcon Console
      condition: event.falcon is defined
      action:
        run_job_template:
          name: 'EDA - Basic Test'
          organization: 'Default'